micronaut:
  application:
    name: kafkactl
  http:
    client:
      read-timeout: 30s
logger:
  levels:
    ROOT: OFF
    io.micronaut.http.client.netty.DefaultHttpClient: OFF # TRACE to see http requests and responses

kafkactl:
  version: 1
  config-path: ${user.home}/.kafkactl
  table-format:
    Namespace:
      - "NAMESPACE:/metadata/name"
      - "CLUSTER:/metadata/cluster"
      - "USER:/spec/kafkaUser"
      - "CONNECTS:/spec/connectClusters"
      - "LDAP:/metadata/labels/support-group"
      - "CONTACTS:/metadata/labels/contacts"
    Topic:
      - "TOPIC:/metadata/name"
      - "RETENTION:/spec/configs/retention.ms%PERIOD"
      - "POLICY:/spec/configs/cleanup.policy"
      - "AGE:/metadata/creationTimestamp%AGO"
    AccessControlEntry:
      - "ACL:/metadata/name"
      - "GRANTED_BY:/metadata/namespace"
      - "GRANTED_TO:/spec/grantedTo"
      - "TYPE:/spec/resourceType"
      - "RESOURCE:/spec/resource"
      - "PATTERN:/spec/resourcePatternType"
      - "PERMISSION:/spec/permission"
      - "AGE:/metadata/creationTimestamp%AGO"
    Connector:
      - "CONNECTOR:/metadata/name"
      - "WORKERS:/spec/connectCluster"
      - "CLASS:/spec/config/connector.class"
      - "TOPICS:/spec/config/topics"
      - "AGE:/metadata/creationTimestamp%AGO"
    RoleBinding:
      - "ROLEBINDING:/metadata/name"
      - "GROUP:/spec/subject/subjectName"
      - "VERBS:/spec/role/verbs"
      - "RESOURCES:/spec/role/resourceTypes"
    ChangeConnectorState:
      - "CONNECTOR:/metadata/name"
      - "STATUS:/status/code"
      - "ERROR_MSG:/status/errorMessage"
    Schema:
      - "SUBJECT:/metadata/name"
      - "ID:/spec/id"
      - "VERSION:/spec/version"
      - "CONFIG:/spec/compatibility"
    SchemaCompatibilityState:
      - "SUBJECT:/metadata/name"
      - "CONFIG:/spec/compatibility"
    KafkaUserResetPassword:
      - "NAMESPACE:/metadata/namespace"
      - "CLUSTER:/metadata/cluster"
      - "USER:/metadata/name"
      - "PASSWORD:/spec/newPassword"
#  api: http://localhost:8080
#  user-token: token
#  current-namespace: namespace_name
