name: Snapshot
on:
  push:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.MICHELIN_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.MICHELIN_DOCKER_HUB_PASSWD }}

      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up GraalVM
        uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: '21.1.0'
          java: 'java11'

      - name: Install native image
        run: gu install native-image

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build jacocoTestReport sonarqube --info

      - name: Push ns4kafka and kafkactl
        run: ./gradlew dockerBuild api:dockerPush cli:dockerPush

      - name: Native image for CLI
        run: ./gradlew :cli:shadowJar :cli:nativeImage

      - name: Upload Linux native Kafkactl
        uses: actions/upload-artifact@v3
        with:
          name: native-image-linux
          path: ${{ github.workspace }}/cli/build/native-image/kafkactl-*

      - name: Upload JAR Kafkactl
        uses: actions/upload-artifact@v2
        with:
          name: jar
          path: ${{ github.workspace }}/cli/build/libs/kafkactl-*.jar

  build-windows:
    runs-on: windows-latest
    environment: Build
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up GraalVM
        uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: '20.3.2'
          java: 'java11'

      - name: Install native image
        run: ${{ env.JAVA_HOME }}\bin\gu.cmd install native-image

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.3

      - name: Native image for CLI
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
          gradlew.bat :cli:shadowJar :cli:nativeImage
        shell: cmd

      - name: Upload Windows native Kafkactl
        uses: actions/upload-artifact@v2
        with:
          name: native-image-windows
          path: ${{ github.workspace }}/cli/build/native-image/kafkactl-*.exe
